### ISSUE TITLE
Crash While Saving

### ISSUE THREAD

**Issue by TrevorAngert** [matgbar/IBI_VizEdit#29] opened 2018-02-27 19:50 UTC
File: 001_T3
Issue: Upon saving the file (NOT saving and closing the application), the program crashed and did not record any of my changes in an output file.
```
Warning: Removed 2 rows containing missing values (geom_point).
Warning: Removed 2 rows containing missing values (geom_path).
Warning: Removed 117 rows containing missing values (geom_path).
Warning: Removed 15 rows containing missing values (geom_path).
Warning: Removed 15 rows containing missing values (geom_path).
Warning: Removed 15 rows containing missing values (geom_path).
Warning: Removed 15 rows containing missing values (geom_path).
Warning: Removed 15 rows containing missing values (geom_path).
Warning: Removed 15 rows containing missing values (geom_path).
Warning: Removed 9 rows containing missing values (geom_path).
Warning: Removed 9 rows containing missing values (geom_path).
Warning: Removed 97 rows containing missing values (geom_path).
Warning: Removed 97 rows containing missing values (geom_path).
Warning: Removed 56 rows containing missing values (geom_path).
Warning: Removed 56 rows containing missing values (geom_path).
Called from: observeEventHandler(...)
Browse[1]> 
```

**Comment by matgbar** [comment] 2018-02-28 20:40
duplicate of issue #30

**Closed by matgbar** 2018-02-28 20:40 UTC
Labels: duplicate
